/* The single fictional dataset for every public surface (landing, demo, and the
   app in demo mode). Company "Northwind", repo "northwind/toolkit". Entirely
   invented and privacy-safe: no real names, repos, paths, or history. Everything
   here is marked source: "demo" so the UI can label it as such. */

import type { Minion, Run, Tool } from "./types";

const TOOLS: Record<string, Tool> = {
  read_repo: { name: "read_repo", permission: "read", description: "Read files and history in the sandboxed repo clone" },
  read_tests: { name: "read_tests", permission: "read", description: "Read the test suite (cannot modify it)" },
  run_tests: { name: "run_tests", permission: "read", description: "Run the test suite in the sandbox" },
  write_patch: { name: "write_patch", permission: "write", description: "Edit source files (never tests)" },
  open_pr: { name: "open_pr", permission: "write", description: "Open a pull request when the gate passes" },
  search_issues: { name: "search_issues", permission: "read", description: "Search the issue tracker" },
  http_get: { name: "http_get", permission: "read", description: "Fetch a URL (allowlisted hosts)" },
  post_summary: { name: "post_summary", permission: "propose", description: "Propose a comment for your approval" },
};

export const MINIONS: Minion[] = [
  {
    id: "m-release-notes",
    name: "Release Notes",
    role: "Release-notes writer",
    purpose: "Draft release notes from merged PRs since the last tag, for a human to approve.",
    instructions:
      "Collect merged PRs since the previous tag, group them by type, and draft concise release notes. Post nothing without approval.",
    status: "ready",
    tools: [TOOLS.read_repo, TOOLS.search_issues, TOOLS.post_summary],
    dataAccess: ["northwind/toolkit (read)", "issue tracker (read)"],
    repo: "northwind/toolkit",
    createdAt: "2026-07-28T14:12:00Z",
    lastActiveAt: "2026-08-08T09:30:00Z",
    runsCount: 6,
    source: "demo",
  },
  {
    id: "m-repo-triage",
    name: "Repo Triage",
    role: "Issue triager and fixer",
    purpose: "Pick up a labelled issue, fix it on a sandboxed clone, and open a PR only when tests prove the fix.",
    instructions:
      "Take one triaged issue, reproduce it, write the smallest correct fix, run the suite, and open a PR only when a previously-failing test passes with no regressions. Otherwise decline with a reason.",
    status: "working",
    tools: [TOOLS.read_repo, TOOLS.read_tests, TOOLS.run_tests, TOOLS.write_patch, TOOLS.open_pr],
    dataAccess: ["northwind/toolkit (read + PR)"],
    repo: "northwind/toolkit",
    createdAt: "2026-07-20T10:00:00Z",
    lastActiveAt: "2026-08-09T16:05:00Z",
    runsCount: 23,
    needsAttention: false,
    source: "demo",
  },
  {
    id: "m-data-quality",
    name: "Data Quality",
    role: "Data-quality checker",
    purpose: "Scan nightly exports for schema drift and null spikes, and propose a fix for approval.",
    instructions:
      "Compare each nightly export against the expected schema and baselines. When a write is needed, stop and ask for approval first.",
    status: "waiting",
    tools: [TOOLS.read_repo, TOOLS.run_tests, TOOLS.write_patch],
    dataAccess: ["northwind/toolkit (read)", "exports bucket (read)"],
    repo: "northwind/toolkit",
    createdAt: "2026-07-22T08:45:00Z",
    lastActiveAt: "2026-08-09T15:40:00Z",
    runsCount: 11,
    needsAttention: true,
    source: "demo",
  },
  {
    id: "m-docs-sync",
    name: "Docs Sync",
    role: "Documentation maintainer",
    purpose: "Keep the README and API docs in sync with exported symbols.",
    instructions: "Detect drift between exported symbols and the docs, and draft the update for review.",
    status: "ready",
    tools: [TOOLS.read_repo, TOOLS.write_patch, TOOLS.open_pr],
    dataAccess: ["northwind/toolkit (read + PR)"],
    repo: "northwind/toolkit",
    createdAt: "2026-07-25T12:00:00Z",
    lastActiveAt: "2026-08-07T11:20:00Z",
    runsCount: 4,
    source: "demo",
  },
  {
    id: "m-uptime",
    name: "Uptime Monitor",
    role: "Monitoring watcher",
    purpose: "Watch the status endpoint and summarise incidents; never act without approval.",
    instructions: "Poll the allowlisted status endpoint, summarise anomalies, and propose an incident note for approval.",
    status: "paused",
    tools: [TOOLS.http_get, TOOLS.post_summary],
    dataAccess: ["status.northwind.example (read)"],
    repo: "northwind/toolkit",
    createdAt: "2026-06-30T09:00:00Z",
    lastActiveAt: "2026-08-05T22:10:00Z",
    runsCount: 41,
    source: "demo",
  },
  {
    id: "m-research",
    name: "Research",
    role: "Research assistant",
    purpose: "Answer a question from allowlisted sources and cite every claim.",
    instructions: "Gather from allowlisted sources only, and attach a citation to each claim. Refuse when sources are weak.",
    status: "ready",
    tools: [TOOLS.http_get, TOOLS.post_summary],
    dataAccess: ["allowlisted docs (read)"],
    repo: "northwind/toolkit",
    createdAt: "2026-08-01T09:00:00Z",
    lastActiveAt: "2026-08-06T13:15:00Z",
    runsCount: 3,
    source: "demo",
  },
];

export const RUNS: Run[] = [
  {
    id: "r-clamp",
    minionId: "m-repo-triage",
    minionName: "Repo Triage",
    ticket: {
      id: "NWT-214",
      title: "Add a clamp(n, min, max) helper",
      body: "Add and export clamp(n, min, max) constraining n to [min, max]. clamp(5,0,10)=5, clamp(-3,0,10)=0, clamp(99,0,10)=10.",
    },
    state: "completed",
    model: "anthropic/claude-opus-4-8",
    startedAt: "2026-08-09T16:00:00Z",
    steps: 7,
    toolCalls: 7,
    baselineTests: { passed: 5, total: 7 },
    finalTests: { ok: true, passed: 7, failed: 0, total: 7 },
    confidence: { score: 0.95, level: "high" },
    risk: { level: "low", score: 0, factors: ["small, self-contained change"] },
    reason: "Adds and exports a correct, minimal clamp using Math.min/Math.max that satisfies every specified case.",
    costUsd: 0.38,
    durationMs: 29257,
    requiresReview: false,
    timeline: [
      { id: "t1", at: "2026-08-09T16:00:00Z", kind: "queued", label: "Picked up NWT-214", phase: "executed" },
      { id: "t2", at: "2026-08-09T16:00:06Z", kind: "plan", label: "Planned the fix", detail: "Add clamp to src/utils.js; verify against the failing test.", phase: "planned" },
      { id: "t3", at: "2026-08-09T16:00:09Z", kind: "tool", label: "read_repo", detail: "src/utils.js, test/utils.test.js", permission: "read", durationMs: 420, phase: "executed" },
      { id: "t4", at: "2026-08-09T16:00:12Z", kind: "test", label: "Baseline: 5/7 passing", detail: "clamp tests fail as expected (function missing).", phase: "executed" },
      { id: "t5", at: "2026-08-09T16:00:20Z", kind: "tool", label: "write_patch", detail: "Added export function clamp(n,min,max).", permission: "write", durationMs: 1500, phase: "executed" },
      { id: "t6", at: "2026-08-09T16:00:26Z", kind: "test", label: "Verification gate: 7/7 passing", detail: "Previously-failing tests pass; no regressions.", phase: "executed" },
      { id: "t7", at: "2026-08-09T16:00:29Z", kind: "verdict", label: "Shipped", detail: "Gate passed. Opened PR on branch minion/nwt-214.", phase: "executed" },
      { id: "t8", at: "2026-08-09T16:00:29Z", kind: "artifact", label: "Pull request + diff", phase: "executed" },
    ],
    artifacts: [
      {
        id: "a-clamp-diff",
        kind: "diff",
        title: "src/utils.js",
        body:
          "@@ -25,4 +25,6 @@ export function parseQueryString(qs) {\n   return out;\n }\n \n-// NWT-214: a clamp(n, min, max) helper is requested but doesn't exist yet.\n+export function clamp(n, min, max) {\n+  return Math.min(Math.max(n, min), max);\n+}",
      },
    ],
    source: "demo",
  },
  {
    id: "r-decline",
    minionId: "m-repo-triage",
    minionName: "Repo Triage",
    ticket: {
      id: "NWT-208",
      title: "Make add() also handle string numbers",
      body: "Vague request with no failing test that pins the intended behavior.",
    },
    state: "declined",
    model: "anthropic/claude-opus-4-8",
    startedAt: "2026-08-09T13:10:00Z",
    steps: 4,
    toolCalls: 3,
    baselineTests: { passed: 7, total: 7 },
    finalTests: { ok: false, passed: 7, failed: 0, total: 7 },
    confidence: { score: 0.3, level: "low" },
    risk: { level: "medium", score: 2, factors: ["no failing test to satisfy", "ambiguous intent"] },
    reason:
      "No previously-failing test specifies the intended behavior, so any change would be an unverifiable guess. Held back rather than ship a doubtful fix.",
    costUsd: 0.12,
    durationMs: 14100,
    requiresReview: false,
    timeline: [
      { id: "d1", at: "2026-08-09T13:10:00Z", kind: "queued", label: "Picked up NWT-208", phase: "executed" },
      { id: "d2", at: "2026-08-09T13:10:05Z", kind: "tool", label: "read_tests", detail: "No test pins the requested behavior.", permission: "read", durationMs: 380, phase: "executed" },
      { id: "d3", at: "2026-08-09T13:10:12Z", kind: "test", label: "Baseline: 7/7 passing", detail: "Nothing is failing to define 'done'.", phase: "executed" },
      { id: "d4", at: "2026-08-09T13:10:14Z", kind: "verdict", label: "Declined", detail: "No verifiable gate. Reported the limitation instead of guessing.", phase: "executed" },
    ],
    artifacts: [],
    source: "demo",
  },
  {
    id: "r-waiting",
    minionId: "m-data-quality",
    minionName: "Data Quality",
    ticket: { id: "NWT-231", title: "Nightly export dropped the region column", body: "Schema drift detected in last night's export." },
    state: "waiting_approval",
    model: "anthropic/claude-opus-4-8",
    startedAt: "2026-08-09T15:35:00Z",
    steps: 3,
    toolCalls: 2,
    timeline: [
      { id: "w1", at: "2026-08-09T15:35:00Z", kind: "queued", label: "Picked up NWT-231", phase: "executed" },
      { id: "w2", at: "2026-08-09T15:35:08Z", kind: "tool", label: "read_repo", detail: "Confirmed the region column is missing from the export mapping.", permission: "read", durationMs: 640, phase: "executed" },
      { id: "w3", at: "2026-08-09T15:35:20Z", kind: "plan", label: "Proposed a one-line mapping fix", phase: "planned" },
      { id: "w4", at: "2026-08-09T15:35:22Z", kind: "approval_requested", label: "Waiting for your approval", detail: "write_patch to src/export/mapping.ts is a guarded action.", permission: "write", phase: "requested" },
    ],
    artifacts: [],
    source: "demo",
  },
  {
    id: "r-recover",
    minionId: "m-repo-triage",
    minionName: "Repo Triage",
    ticket: { id: "NWT-219", title: "slugify collapses consecutive spaces", body: "slugify('a   b') should be 'a-b', not 'a---b'." },
    state: "completed",
    model: "anthropic/claude-opus-4-8",
    startedAt: "2026-08-09T11:02:00Z",
    steps: 9,
    toolCalls: 8,
    baselineTests: { passed: 6, total: 8 },
    finalTests: { ok: true, passed: 8, failed: 0, total: 8 },
    confidence: { score: 0.9, level: "high" },
    risk: { level: "low", score: 0, factors: ["single-line regex change"] },
    reason: "Collapsing runs of whitespace with /\\s+/g fixes the case with no regression.",
    costUsd: 0.29,
    durationMs: 41200,
    timeline: [
      { id: "c1", at: "2026-08-09T11:02:00Z", kind: "queued", label: "Picked up NWT-219", phase: "executed" },
      { id: "c2", at: "2026-08-09T11:02:07Z", kind: "tool", label: "run_tests", detail: "Sandbox image pull timed out.", permission: "read", durationMs: 30000, phase: "failed" },
      { id: "c3", at: "2026-08-09T11:02:38Z", kind: "error", label: "Step failed: sandbox timeout", detail: "A transient infrastructure error, not a code problem.", phase: "failed" },
      { id: "c4", at: "2026-08-09T11:02:40Z", kind: "retry", label: "Retrying from the last checkpoint", detail: "Bounded retry (attempt 2 of 3).", phase: "recovered" },
      { id: "c5", at: "2026-08-09T11:02:52Z", kind: "test", label: "Baseline: 6/8 passing", phase: "executed" },
      { id: "c6", at: "2026-08-09T11:03:10Z", kind: "tool", label: "write_patch", detail: "Replaced / /g with /\\s+/g in slugify.", permission: "write", durationMs: 1400, phase: "executed" },
      { id: "c7", at: "2026-08-09T11:03:18Z", kind: "test", label: "Verification gate: 8/8 passing", phase: "executed" },
      { id: "c8", at: "2026-08-09T11:03:20Z", kind: "verdict", label: "Shipped", detail: "Recovered from the transient failure and shipped a verified fix.", phase: "executed" },
      { id: "c9", at: "2026-08-09T11:03:20Z", kind: "artifact", label: "Pull request + diff", phase: "executed" },
    ],
    artifacts: [
      { id: "a-slug", kind: "diff", title: "src/utils.js", body: "@@\n-  return input.trim().toLowerCase().replace(/ /g, \"-\");\n+  return input.trim().toLowerCase().replace(/\\s+/g, \"-\");" },
    ],
    source: "demo",
  },
];

export function getMinion(id: string): Minion | undefined {
  return MINIONS.find((m) => m.id === id);
}
export function getRun(id: string): Run | undefined {
  return RUNS.find((r) => r.id === id);
}
export function runsForMinion(id: string): Run[] {
  return RUNS.filter((r) => r.minionId === id);
}
